language: node_js
node_js: "stable"

sudo: required

branches:
  only:
    - master
services:
  - docker

before_install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
  - chmod +x kubectl && sudo mv kubectl /usr/local/bin/kubectl
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker build -f docker/barbearia.dockerfile -t thileal/barbearia:$TRAVIS_BUILD_NUMBER .
  - npm update

install:
  - npm install

script:
  - npm test
  - docker push thileal/barbearia:$TRAVIS_BUILD_NUMBER
  - bash scripts/update-kube.sh

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
