version: '3'

networks:
  barbearia-network:
    driver: bridge

services:
  barbearia:
    build:
      dockerfile: ./docker/barbearia.dockerfile
      context: .
    image: thileal/barbearia
    container_name: barbearia-server
    ports:
      - 3000:3000
    environment:
      DB_DIALECT: postgres
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: barbearia-db
      DB_PORT: 5432
    restart: unless-stopped
    networks:
      - barbearia-network
    depends_on:
      - "postgres"

  postgres:
    image: postgres:12.2-alpine
    container_name: barbearia-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: barbearia-db
    restart: always
    volumes:
      - $PWD/database/data:/var/lib/postgresql/data
    networks:
      - barbearia-network