apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: barbearia-ingress
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  tls:
  - hosts:
    - barbeariacompasso.tk
    secretName: barbearia-tls
  rules:
  - host: barbeariacompasso.tk
    http:
      paths:
      - backend:
          serviceName: svc-barbearia
          servicePort: 80